app/models.py
import os
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from time import time

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(48), unique = True, index=True)
    email = db.Column(db.String(48),unique=True, index = True)
    hash_pass = db.Column(db.String(255)) 

    @property
    def password(self):
        raise AttributeError("You cannot read password attribute")

    @password.setter
    def password(self,password):
        self.hash_pass = generate_password_hash(password)
    
    def set_password(self,password):
        self.hash_pass = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.hash_pass,password)  
    
    def get_reset_password_token(self, expires_in=1800):
        return jwt.encode({'reset_password':self.id, 'exp':time()+expires_in}, os.environ.get('SECRET_KEY'), algorithm='HS256').decode('utf-8')
    
    @staticmethod
    def verify_reset_password(token):
        try:
            id = jwt.decode(token, os.environ.get('SECRET_KEY'),algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)
class feedback(db.Model):
    __tablename__ = 'feedback'
    id = db.Column(db.Integer,primary_key = True)
    subscriber_name = db.Column(db.String(50))
    subscriber_email = db.Column(db.String(255), unique = True)  

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
# from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_simplemde import SimpleMDE
from config import config_options

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
# photos = UploadSet('photos',IMAGES)
simple = SimpleMDE()

def create_app(config_name):
    
    app = Flask(__name__)

    # app configurations
    app.config.from_object(config_options[config_name])

    # initializing flask extensions
    config_options[config_name].init_app(app)
    db.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)

    # Register the main app blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # adding the admin app blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for, flash, abort
from . import main
from flask_login import login_required,current_user

@main.route("/")
def welcome():
    return render_template('welcome.html', title = 'Welcome')
    
@main.route("/home")
def home():
    title = 'Home | Hype App'

    return render_template('index.html', title=title)
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("account.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('account.html',form =form)

app/templates/account.html
{% extends 'base.html'%}
{% block content %}

<style>
    body {
        background-color: #D7D8DA;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-5 profile_pic">
            {% if user.profile_pic_path %}
            <p class="user-tag"> <strong>Username: </strong>{{user.username|capitalize}} </p>
            <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <img src="{{url_for('static',filename = 'img/avatar.jpeg')}}" alt="" class="img-thumbnail">
            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
        <div class="col-md-7">
            <h4>Bio Information</h4>
            {% if user.bio %}
            <p> {{user.bio}} </p>
            {% else %}
            <p>{{user.username}} has no bio</p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit Bio</a><br>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}



<ul class="nav navbar-nav navbar-right topright">
    <li>
        <a href="{{url_for('auth.register')}}">
            <span class="glyphicon glyphicon-user"></span> Sign UP</a>
    </li>
    <li>
        <a href="{{url_for('auth.login')}}">
            <span class="glyphicon glyphicon-log-in"></span> Log In</a>
    </li>
    <li >
        <a href="{{ url_for('auth.logout')}}">
            <i class="fa fa-sign-out"></i> Sign out</a>
            <li class="nav-item">
              <a  href="{{ url_for('auth.login')}}">
              <i class="fa fa-user-plus"></i> Account</a>
            </li>

</ul>

<div class="head">
    <h1>
        <span class="fancy">
            <span>Hype App</span>
        </span>
    </h1>
    <p>
        <em>The official Hype</em>
    </p>

</div>



<div class="links" style="list-style:none">
        <ul>
            <a class="button" href="#video">Venues</a>
            <a class="button" href="#parks">Parks</a>
            <a class="button" href="#resort">Resorts</a>
        </ul>
    </div> 

<div class="col-md-12 second" name="video">
    <img class="vida" src="{{url_for('static',filename='Images/giphy (1).gif')}}">
</div>

<div class="container-fluid" style="padding-top:60vh">
    <div class="col-md-9">
        <div class="col-md-12">
            <div class="artists">
                <img href="#video" src="{{url_for('static',filename='Images/image10.jpeg')}}">
                <p><strong>Book Your Venue</strong><br>

                    Whether you are planning an intimate dinner for friends,<br> a corporate luncheon or an
                    <br>extravagant soirée, sbe’s best-in-class service,<br> versatile venues and award-winning
                    catering will guarantee that your event <br>will be a success.

                    For private parties and large groups planning <br>an event</p>
                <ul>
                        <a><button class="myButton">Readmore</button></a>
                </ul>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
             <script>
                 $(document).ready(function(){
              $("button").click(function(){
                   $("p").toggle();
                  });
                });
              </script> 
            </div>
        </div>
        <div class="col-md-12">
            <div class="Djs">
                <img href="#parks" src="{{url_for('static',filename='Images/image11.jpeg')}}">
                <p>Something old, something new, something borrowed, something <br>unforgettable. From rooftop
                    receptions to beachfront brunches, <br>our signature collection of hotels, <br>restaurants and nightlife
                    venues provide the perfect setting for <br>your big event. Featuring award-winning <br>catering, premium
                    mixology and best-in-class service, our team of event <br>experts will help you host one-of-a-kind
                    celebrations that you won’t soon forget.</p>
                <br>
                <ul>
                        <a><button class="myButton">Readmore</button></a>


                </ul>
            </div>
        </div>

        <div class="col-md-12">
            <div class="Producers">
                <img href="#resort" src="{{url_for('static',filename='Images/image12.jpeg')}}">
                <p>A blend of African heritage and boldness welcomes visitors with the<br>
                     down-to-earth warmth of a much-loved home away from home. <br>
                    Spacious interiors are styled with a varied mix of rich colours, and inviting textures and layers, making Naivasha Kongoni Lodge an idyllic retreat.<br>
                     Naivasha Kongoni Lodge offers guests the ultimate in personal comfort, luxury and innovative business and leisure facilities.
                
                    
                    <ul>
                            <a><button class="myButton">Readmore</button></a>
                    </ul>
                    <style>
                    
                    </style>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="footer">
    <br>
    <div class="images">
        <img src="{{url_for('static',filename='Images/facebook1.png')}}" width="40px" height="40px">
        <img src="{{url_for('static',filename='Images/twitter1.png')}}" width="40px" height="40px">
        <img src="{{url_for('static',filename='Images/linkedin.png')}}" width="40px" height="40px">
    </div>

    <div id="Contact" class="tabcontent">

        <a href="mailto:beatshub@gmail.com ">
            <h4>Contact us :+254712345679</h4>
        </a>

    </div>

    <div id="Policy" class="tabcontent">
    </div>

    <div id="Work" class="tabcontent">
    </div>

    <div id="Legal" class="tabcontent">
    </div>

    <p>A world class Hype platform</p>
    <p> Hype app 2020.All rights reserved.</p>
    <br>

    <a href="#" class="float">
        <i class="fa fa-envelope my-float"></i>
    </a>
    <div class="label-container">
        <div class="label-text">Feedback</div>
        <i class="fa fa-play label-arrow"></i>
    </div>
</div>


{% endblock %}

app/templates/welcome.html
{% extends 'base.html'%}
{% block content %}
<style>
    body {
    background-image: url("https://bit.ly/2T3qimu");
    background-size: cover;
    height: 100%;
    
    
}

.welcome {
    text-align: center;

}

.welcome h1 {
    font-family: 'Bilbo Swash Caps';
    font-size: 150px;
    color: black;
}

.welcome h2 {
    font-family: 'Cinzel';
    font-size: 30px;
    color: black;
}

.welcome a {
    font-family: 'Mukta';
}

.welcome a:hover {
    color: white;
}
</style>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary mb-5">
        <a class="navbar-brand" style="color: white;" href="/">Hype app</a>
        </button>
      </nav>
      <div class="container-fluid welcome-page">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 welcome"><br><br><br><br><br><br><br><br>
                        <h1>{{title}}</h1>
                        <h2> To Hype App</h2>
                        {% if current_user.is_authenticated%}
                        <a id="start" class="btn btn-danger animated infinite flash" href="{{url_for('auth.register')}}">Sign up</a>
                        {% else %}
                        <a id="start" class="btn btn-danger animated infinite flash" href="{{url_for('auth.register')}}"> Sign up</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
{%endblock%}